### PR TITLE
Revert "Ignore Bots"

### PR DESCRIPTION
**Pull request by z64**
changed my mind

### CODE REVIEW

**Review by Daniel-Worrall — CHANGES_REQUESTED** [review]
revert this

**Comment by z64** [comment]
review pls

**Comment by z64** [comment]
thank you you are a beacon of hope in the open source commun tiy

**Comment by ghost** [comment]
ok

**Comment by z64** [comment]
@TrenchFroast please don't spam on our repo, thanks

**Comment by Daniel-Worrall** [comment]
Our? You merge a couple of their PR's, soon they think they own the repo.

**Comment by z64** [comment]
@Daniel-Worrall please don't spam my repo, thanks

**Comment by z64** [comment]
redacted message

**Comment by z64** [comment]
image

**Comment by Daniel-Worrall** [comment]
Excuse me sir, this repo is for serious comments only.

**Pull request merged**
